# Generated by Django 5.1.2 on 2024-10-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='criada',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
